name: build
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checks out code from Github.
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.1"
      - name: Build
        run: cd src && hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
